            <div class="container-skew">
                <div class="container-fluid px-0 text-justify-cookie" style="width:100% !important;">
                    <h2 class="text-center judul-service">	KETENTUAN PENYEDIAAN LAYANAN <br>
                    XL HOME FIBER BROADBAND
                    </h2>
                    <p class="content">Ketentuan Penyediaan Layanan XL HOME Fiber Broadband yang ditetapkan di bawah ini mengatur Syarat dan Ketentuan yang ditetapkan oleh PT XL Axiata selaku penyedia layanan. Pelanggan diwajibkan untuk membaca dengan seksama karena dapat berdampak kepada hak dan kewajiban Pelanggan dalam menggunakan Layanan.
                    </p>
                    <p class="content">Dengan <div class="container-fluid px-0 text-justify-cookie" style="width:100% !important;">
                    <h2 class="text-center judul-service">	KETENTUAN PENYEDIAAN LAYANAN <br>
                    XL HOME FIBER BROADBAND
                    </h2>
                    <p class="content">Ketentuan Penyediaan Layanan XL HOME Fiber Broadband yang ditetapkan di bawah ini mengatur Syarat dan Ketentuan yang ditetapkan oleh PT XL Axiata selaku penyedia layanan. Pelanggan diwajibkan untuk membaca dengan seksama karena dapat berdampak kepada hak dan kewajiban Pelanggan dalam menggunakan Layanan.
                    </p>
                    <p class="content">Dengan mendaftar dan/atau menggunakan Layanan XL HOME, maka Pelanggan dianggap telah membaca, mengerti, memahami dan menyetujui semua isi dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband. Ketentuan ini merupakan salah satu bentuk kesepakatan yang dituangkan dalam sebuah perjanjian yang sah antara Pelanggan dengan PT XL Axiata. Jika Pelanggan tidak menyetujui salah satu, sebagian, atau seluruh isi dari Ketentuan Penyediaan Layanan XL HOME Fiber Broadband, maka Pelanggan tidak diperkenankan menggunakan Layanan sebagaimana yang dimaksud.</p>
                    <h2 class="header">	PENYEDIAAN LAYANAN | SERVICE DELIVERY</h2>
                    <p class="content">1.	PT XL Axiata atau XL adalah perusahaan penyelenggara jasa akses internet, didirikan berdasarkan peraturan dan ketentuan hukum yang berlaku di Negara Republik Indonesia.</p>
                    <p class="content">2.	XL HOME Fiber Broadband atau “Layanan” adalah layanan telekomunikasi dalam bentuk data, suara, dan gambar berupa penyediaan Jasa Akses Internet dan Jasa Internet Teleponi untuk keperluan Publik, Email, dan Jaringan Komunikasi Data, termasuk, namun tidak terbatas, pada produk turunan lainnya dimasa mendatang.</p>
                    <p class="content">3.	Pelanggan adalah Pihak yang terdaftar sebagaimana tercantum dalam Formulir Pendaftaran yang disediakan oleh XL HOME, baik atas nama diri sendiri, perusahaan maupun pihak yang diwakili berdasarkan surat kuasa dan/atau dokumen pembuktian lainnya yang sah secara hukum dan peraturan yang berlaku.</p>
                    <p class="content">4.	Perangkat XL HOME adalah Optical Network Terminal (ONT), Set Top Box/Dekoder Digital, Remote Control dan perangkat pendukung lainnya, termasuk, tetapi tidak terbatas, pada peralatan dan perlengkapan lain yang dibutuhkan dimasa yang akan datang yang terdapat di lokasi Pelanggan, selama peralatan dan perlengkapan tersebut tercatat sebagai milik XL HOME.</p>
                    <p class="content">5.	Lokasi adalah lokasi tempat penyediaan layanan XL HOME Fiber Broadband sebagaimana yang tercantum dalam Formulir Pendaftaran/Dokumen pendukung lainnya.</p>
                    <p class="content">6.	XL HOME akan memberikan Username dan Password (SSID dan password) untuk aksestabilitas dalam menggunakan dan menikmati Layanan. Pelanggan bertanggung jawab sepenuhnya terhadap segala aktivitas penggunaan Layanan dan menjaga kerahasiaan password sebagai suatu informasi rahasia yang patut dijaga kerahasiaannya.</p>
                    <p class="content">7.	Pelanggan mengakui dan bertanggung jawab secara penuh bahwa informasi dan dokumen yang diserahkan kepada XL HOME sebagai suatu persyaratan pendaftaran Layanan merupakan dokumen yang sah secara hukum dan memiliki kebenaran yang sejati.</p>
                    <p class="content">8.	XL HOME akan melakukan proses instalasi untuk Pelanggan apabila telah terpenuhinya syarat-syarat yang ditetapkan oleh XL HOME, termasuk diantarannya persyaratan teknis, Formulir Berlangganan, kopi Identitas Pelanggan (KTP/SIM/KITAS), pembayaran pertama sesuai jenis layanan yang dipilih dan dokumen lainnya.</p>
                    <p class="content">9.	Pelanggan berhak untuk menikmati segala manfaat dan keuntungan yang diperoleh melalui penyediaan Layanan, dengan tetap memperhatikan Syarat dan Ketentuan yang diberlakukan oleh XL HOME sebagai penyedia Layanan, termasuk peraturan dan ketentuan hukum yang berlaku di wilayah hukum Republik Indonesia.</p>
                    <p class="content">10.	Pelanggan dengan ini mengakui dan menyatakan bahwa XL HOME dibebaskan dari bentuk pertanggungjawaban, atas layanan yang digunakan oleh Pelanggan atas ketidakcocokan peralatan dan perlengkapan yang digunakan oleh Pelanggan untuk menikmati Layanan termasuk jika Pelanggan melakukan hubungan kerjasama dengan Pihak Lain dan/atau telah terjadi suatu kombinasi antara perangkat milik XL HOME dengan perangkat milik Pihak Ketiga yang tidak diatur dalam Perjanjian ini baik secara sebagian maupun menyeluruh yang akan mempengaruhi kualitas Layanan yang dinikmati oleh Pelanggan.</p>
                    <p class="content">11.	Pelanggan dengan ini memahami segala resiko atas penggunaan dan/atau ketidaksanggupan Layanan yang disediakan oleh XL HOME, untuk itu Pelanggan bersedia membebaskan XL HOME dari segala tuntutan ganti rugi baik yang bersifat materil maupun inmateril dan bentuk pertanggung jawaban lain yang ditimbulkan dari adanya resiko tersebut.</p>
                    <p class="content">12.	XL HOME akan melakukan proses instalasi sesuai jadwal pengerjaan yang telah disepakati oleh Pelanggan, dengan standar prosedur yang telah ditetapkan oleh XL HOME, dimana selama proses instalasi berlangsung, Pelanggan ataupun perwakilannya wajib berada di lokasi dan mengawasi seluruh proses Instalasi hingga selesai.</p>
                    <p class="content">13.	Selama Pelanggan masih terdaftar sebagai pengguna Layanan, maka Pelanggan memiliki kewajiban untuk menjaga dan merawat Perangkat XL HOME yang ditempatkan di lokasi. Apabila terjadi kerusakan/kehilangan atas Perangkat pendukung layanan XL HOME, maka XL HOME akan membebankan biaya penggantian/perbaikan kepada Pelanggan.</p>
                    <h2 class="header">	LARANGAN DAN SANKSI</h2>
                    <p class="content">14.	Demi kenyamanan bersama pengguna Internet, Pelanggan tidak diperkenankan untuk melakukan tindakan-tindakan yang disengaja sehingga mengganggu atau merugikan pihak lainnya, termasuk tetapi tidak terbatas pada:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Tindakan atau usaha sehingga menimbulkan gangguan pada suatu jaringan atau sistem komputer atau menimbulkan ketidaknyamanan pihak yang berkepentingan;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Memberikan keterangan palsu terhadap data dan informasi yang dibutuhkan termasuk identitas diri terkait penyediaan Layanan yang disediakan oleh XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Menyewakan, menjual kembali, dan/atau mengalihkan penggunaan Layanan XL HOME (baik sebagian atau seluruhnya) kepada pihak lain manapun tanpa persetujuan dari XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Melakukan perubahan apapun terhadap konfigurasi Layanan XL HOME dan/atau perangkat pendukung yang disediakan oleh XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Tindakan atau usaha lain yang dapat dianggap telah melanggar hukum dan peraturan yang berlaku di wilayah yurisdiksi Republik Indonesia.</li>
                    </ol>
                    <p class="content">15.	Pelanggan dilarang melakukan tindakan yang dapat menimbulkan gangguan pada jaringan dan atau sistem elektronik lainnya yang berkaitan atau memiliki keterkaitan dengan penyediaan Layanan yang disediakan oleh XL HOME.</p>
                    <p class="content">16.	XL HOME berhak untuk memutuskan Layanan sebelum Pelanggan menyatakan untuk melakukan pengakhiran masa berlangganan dalam keadaan:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Pelanggan telah melakukan pelanggaran terhadap larangan-larangan sebagaimana yang tercantum dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Adanya permintaan dari pejabat penyidik negara guna kepentingan penyidikan sesuai dengan peraturan dan ketentuan hukum yang berlaku di Negara Republik Indonesia;</li>
                    </ol>
                    <p class="content">17.	Pemutusan Layanan sebagaimana dijelaskan pada pasal 16, akan diikuti/didahului dengan pemberitahuan/peringatan sebelumnya kepada Pelanggan.</p>
                    <p class="content">18.	Pelanggan dilarang untuk memberikan hadiah, tips, dan/atau pemberian lainnya yang dapat dikategorikan sebagai suatu pemberian yang tidak diatur dalam ketentuan penyediaan Layanan kepada petugas instalasi, staff, affiliasi, pegawai, manager, dan jajaran direksi XL HOME.</p>
                    <h2 class="header">		JAMINAN DAN TANGGUNG JAWAB </h2>
                    <p class="content">19.	XL HOME bertanggung jawab penuh atas kualitas layanan yang diberikan kepada Pelanggan terkecuali akibat adanya gangguan yang timbul karena kelalaian Pelanggan dan/atau dilaksanakannya tindakan pengamanan darurat dan peristiwa lainnya yang terjadi diluar kendali XL HOME (force majeure) sebagai penyedia Layanan termasuk tetapi tidak terbatas pada suatu akibat dari adanya putusan pengadilan, ketentuan dan peraturan hukum yang baru dan berlaku surut maupun adanya keputusan dari Instansi Pemerintah yang berwenang dalam mengeluarkan suatu kebijakan peraturan perundang-undangan yang berkaitan dengan penyediaan Layanan XL HOME diwaktu yang akan datang.</p>
                    <p class="content">20.	XL HOME berhak sewaktu-waktu mengurangi, menambah atau mengubah Layanannya termasuk dengan perubahan harga dikemudian hari, dengan pemberitahuan terlebih dahulu melalui pengumuman di salah satu saluran XL HOME, email blast, sms broadcast, website, dan teks berjalan (scrolling text), atau pada media-media lainnya, kecuali perubahan yang dilakukan pihak ketiga.</p>
                    <p class="content">21.	Pelanggan wajib menjaga dan memelihara perangkat milik XL HOME di lokasi Pelanggan agar tetap berfungsi dan dalam keadaan baik serta layak pakai terhitung sejak tanggal berlangganan sampai dengan dikembalikannya ke XL HOME akibat berakhirnya masa Berlangganan dengan XL HOME. Apabila terjadi kerusakan/kehilangan atas Perangkat pendukung Layanan XL HOME karena sebab apapun, kecuali akibat dari keadaan Force Majeure, maka XL HOME akan membebankan biaya penggantian/perbaikan kepada Pelanggan.</p>
                    <p class="content">22.	Apabila perangkat milik XL HOME yang ditempatkan di lokasi Pelanggan hilang, rusak atau musnah karena sebab apapun kecuali akibat dari keadaan Force Majeure dan kelalaian XL HOME, maka Pelanggan harus mengganti perangkat tersebut atau mengganti sesuai dengan harga perangkat saat kehilangan atau kerusakan terjadi.</p>
                    <p class="content">23.	Guna meningkatkan kualitas layanan yang disediakan kepada para Pelanggan serta demi pengamanan jaringan internal, XL HOME berhak untuk melakukan perawatan berkala (scheduled maintenance) yang akan diumumkan selambatnya 3 (tiga) hari kalender. XL HOME juga berhak untuk melakukan tindakan pengamanan darurat yang akan diikuti pemberitahuan melalui email dan/atau SMS ke kontak masing-masing Pelanggan.</p>
                    <p class="content">24.	Untuk keperluan pemeriksaan kualitas Layanan XL HOME, Pelanggan wajib memperkenankan XL HOME untuk dapat memasuki dan memeriksa perangkat di lokasi Pelanggan. Sesuai dengan surat perintah kerja yang ditunjukan oleh karyawan XL HOME ke Pelanggan saat dilakukan kunjungan.</p>
                    <h2 class="header">BIAYA DAN PEMBAYARAN</h2>
                    <p class="content">25.	Atas penyediaan Layanan sesuai dengan jenisnya masing-masing, maka XL HOME berhak atas biaya-biaya berikut ini: </p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Biaya berlangganan, yang wajib dilunasi Pelanggan sebelum Layanan dimulai; First payment.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Biaya bulanan, yang sesuai dengan jenis Layanan dan/atau fasilitas tambahan menurut permintaan Pelanggan, wajib dilunasi pada tanggal jatuh tempo di setiap bulan penagihan melalui Transfer, ATM atau metode pembayaran lainnya.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Biaya tambahan akan dikenakan untuk permintaan tambahan perangkat, material dan service tambahan saat pemasangan dan/atau selama masa berlangganan.</li>
                        <li class="content" style="list-style-type: lower-alpha;">d.	Biaya tambahan akan dikenakan untuk layanan kunjungan teknisi ke rumah pelanggan selama masa berlangganan atas permintaan pelanggan (diluar kendala yang disebabkan oleh gangguan layanan XL Home).</li>
                    </ol>
                    <p class="content">26.	Daftar biaya - biaya tambahan XL HOME adalah sebagai berikut: <br>XL HOME surcharge fee list are as follows: </p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Penarikan kabel ethernet diluar standard XL HOME atau melebihi 1 meter, akan dikenakan biaya tambahan sebesar Rp. 15.000 (lima belas ribu rupiah)/meter;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penarikan kabel Drop/ kabel optic diluar standart XL HOME atau melebihi 100 meter, akan dikenakan biaya tambahan sebesar Rp. 10.000 (Sepuluh ribu rupiah) / meter;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penggantian kerusakan perangkat Set Top Box XL HOME akan dikenakan biaya sebesar Rp. 1.000.000 (satu juta rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penggantian kerusakan ONT XL HOME akan dikenakan biaya sebesar Rp. 1.000.000 (satu juta rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penggantian kerusakan kabel HDMI, Remote Control, kabel RCA dan kabel adapter akan dikenakan biaya sebesar Rp. 500.000 (lima ratus ribu rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Perpindahan perangkat di lokasi yang sama atau ke lokasi baru, akan dikenakan biaya relokasi sebesar Rp. 500.000 (lima ratus ribu rupiah).</li>
                    </ol>
                    <p class="content">27.    Penagihan atas penggunaan Layanan XL HOME akan dilakukan di setiap Billing Cycle (Periode Tagihan) dan diinformasikan oleh XL HOME melalui Faktur Tagihan/Invoice yang dikirimkan ke email Pelanggan.</p>
                    <p class="content">28.	Pelanggan tidak diperkenankan untuk melakukan pembayaran tagihan dalam bentuk apapun melalui karyawan dan/atau petugas XL HOME di lokasi pemasangan.</p>
                    <p class="content">29.	Minimum masa berlangganan adalah 12 (dua belas) bulan, apabila sewaktu-waktu Pelanggan menginginkan pengakhiran Layanan sebelum 12 (dua belas) bulan masa berlangganan, maka Pelanggan wajib terlebih dahulu memberikan pemberitahuan selambat-lambatnya 14 (empat belas) hari sebelum tanggal pemutusan dan wajib membayar biaya penalti sebesar Rp 1.000.000,- (satu juta rupiah) dan melunasi semua pembayaran yang tertunggak.</p>
                    <p class="content">30.	Dengan Pemutusan Layanan dan/atau telah berakhirnya masa berlangganan, maka perangkat XL HOME yang ditempatkan di lokasi Pelanggan wajib dikembalikan oleh Pelanggan kepada XL HOME dalam keadaan lengkap dan tanpa adanya cacat baik yang terlihat maupun yang tersembunyi.</p>
                    <h2 class="header">	HUKUM DAN LAIN-LAIN</h2>
                    <p class="content">31.	Tidak dilaksanakannya sebagian atau seluruh Ketentuan ini oleh salah satu atau kedua belah pihak tidak termasuk sebagai pelanggaran atas Ketentuan jika hal-hal tersebut disebabkan oleh keadaan Force Majeure (keadaan memaksa).</p>
                    <p class="content">32.	Yang termasuk Force Majeure adalah kejadian-kejadian yang tidak dapat diduga, berdampak luas dan yang terjadi diluar kekuasaan manusia, antara lain termasuk tetapi tidak terbatas pada peristiwa-peristiwa atau bencana alam, wabah penyakit (epidemi), pemberontakan, huru-hara, perang, kebakaran, sabotase, pemogokan umum, petir, putus aliran listrik umum diluar kemampuan para pihak untuk mengatasinya.</p>
                    <p class="content">33.	Isi dan pelaksanaan ketentuan ini tunduk kepada peraturan dan hukum yang berlaku di wilayah jurisdiksi Republik Indonesia.</p>
                    <p class="content">34.	Dalam hal timbulnya perselisihan akibat isi dan pelaksanaan ketentuan ini, maka akan diselesaikan secara musyawarah langsung antara Pelanggan dan XL HOME.</p>
                    <p class="content">35.	Apabila Pelanggan dan XL HOME tidak dapat menyelesaikan perselisihan secara musyawarah, maka Pelanggan dan XL HOME sepakat untuk menempuh jalur hukum dan menunjuk Pengadilan Negeri Jakarta Selatan sebagai domisili hukum umum dan tetap.</p>
                    <p class="content">36.	XL HOME berhak untuk memberikan informasi mengenai identitas Pelanggan terdaftar kepada pejabat penyidik yang berwenang dalam keadaan tertentu sesuai dengan peraturan dan hukum yang berlaku di wilayah Republik Indonesia.</p>
                    <p class="content">XL HOME reserves the right to provide information on the identity of registered customers to the investigation authorities in certain circumstances in accordance with the laws and regulations applicable in the territory of the Republic of Indonesia.</p>                
                    <p class="content">37.	XL Home tidak akan membagikan informasi pribadi dengan perusahaan, organisasi, dan individu diluar XL Home, kecuali dalam situasi yang dijelaskan dalam Kebijakan Privasi XL Axiata. XL Home dapat membagikan informasi non-pribadi kepada pihak ketiga di luar XL Home, seperti penyedia konten atau situs terhubung. Informasi ini dapat digunakan untuk mempromosikan XL Home, mitra layanan dan konten, atau digunakan untuk peningkatan layanan atau konten.</p>
                    <p class="content">38.	Pemutusan layanan akibat permintaan atau kelalaian Pelanggan dalam memenuhi ketentuan ini tidak menghapuskan kewajiban yang terhutang atas penggunaan layanan.</p>
                    <p class="content">39.	Apabila telah terjadi suatu pertentangan atau ditemukannya ketidaksesuaian antara Ketentuan Penyediaan Layanan XL HOME Fiber Broadband dengan Dokumen lain yang masih saling berhubungan dalam penyediaan Layanan yang disediakan oleh XL HOME, maka yang berlaku adalah ketentuan-ketentuan yang berlaku dalam Ketentuan Penyediaan Layanan Fiber Broadband ini.</p>
                    <p class="content">40.	Apabila terdapat ketentuan dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband yang secara khusus mengatur bahwa ketentuan alternatif sebagaimana yang terdapat dalam Dokumen-dokumen yang berkaitan dengan penyediaan Layanan XL HOME kepada Pelanggan lebih berlaku atas ketentuan yang terdapat didalam Ketentuan Penyediaan Layanan Fiber Broadband ini, maka ketentuan pengganti yang terdapat didalam dokumen tersebutlah yang akan berlaku selama hanya berlaku atas Dokumen-dokumen sebagaimana yang dimaksud tersebut dan bukan merupakan variasi dari Ketentuan manapun dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband.</p>
                    <p class="content">41.	XL HOME memiliki hak untuk mengubah baik secara sebagian maupun menyeluruh terhadap isi dari Ketentuan Penyediaan Layanan XL HOME Fiber Broadband di kemudian hari. Setiap perubahan dapat dilihat di website XL Home.</p>
                    <p class="content"></p>
            
                    <h2 align="center">	TERMS OF SERVICE <br>
                        XL HOME FIBER BROADBAND 
                    </h2>
                    <p class="content">The following Terms of Service for XL Home Fiber Broadband is managed to set the terms and conditions of PT XL Axiata as a service provider. Customers are required to read carefully as it affect the rights and obligations of customers while using the Service.  </p>
                    <p class="content">By registering and/or using XL HOME service, customers are considered to have read, understand, acknowledge, and agree to the contents in Terms of Service for XL HOME Fiber Broadband. The Terms of Service is a legal agreement set forth between the Customer and PT XL Axiata. If the Customer does not agree to one, some, or all of the contents in Terms of Service for XL HOME Fiber Broadband, then Customer may not use the service as intended.</p>
                    <h2 class="header">SERVICE DELIVERY</h2>
                    <p class="content">1. PT XL Axiata or XL is an internet service provider company, established under the legal provisions applicable in the Republic of Indonesia.</p>
                    <p class="content">2. XL HOME Fiber Broadband or “Services” are telecommunication services in the form of data, sound, and images as Internet Access and Internet Telephony Service Provider intended for public, email, and data communications network, including, but not limited, to other derivative products in the future.</p>
                    <p class="content">3. Customers are the registered Parties as contained in the Registration Form provided by XL HOME, whether on its own behalf, the company or the parties by the power of attorney and / or other evidentiary documents that valid legally and according to regulations.</p>
                    <p class="content">4. XL HOME devices are (Optical Network Terminal (ONT), Set Top Box / Digital Decoder, Remote Control, and other supporting devices, including, but not limited to, hardware and other equipment needed in the future located in Customer’s location, as long as the equipment and supplies are listed as owned by XL HOME.</p>
                    <p class="content">5. Location is the location where XL HOME Fiber Broadband service is provided as written in the Registration Form / Other supporting documents.</p>
                    <p class="content">6. XL HOME will provide the Username and Password that is unique to Customer for accessibility in using and enjoying our Services. Customer is solely responsible for all activities in using our Services and maintaining the confidentiality of the password as a secret information that should be kept confidential.</p>
                    <p class="content">7. Customer acknowledges and fully responsible that the information and documents submitted to the XL HOME as a Service registration requirement is a document that is legally valid and has the real truth.</p>
                    <p class="content">8. XL HOME will do the installation process for the customer if the requirements set by XL HOME have been fulfilled, including the technical requirements in the Subscription Form, copy of your ID (KTP/SIM/KITAS), Receipt of first payment based on the package that you choose and other documents.</p>
                    <p class="content">9. Customers are entitled to receive all the benefits and advantages obtained through the terms of service, with regard to the terms and conditions imposed by XL HOME as a service provider, including legal provisions applicable in the jurisdiction of the Republic of Indonesia.</p>
                    <p class="content">10. Customer hereby acknowledges and states that XL HOME is released from the accountability for services used by the Customer, regarding the incompatibility of equipment and supplies used by the Customer to enjoy the Services including if the Customer has conducted a cooperative relationship with the Other and / or there has been a combination of XL HOME-owned devices with devices that belong to Third Party that is not mentioned under this Agreement either in part or a whole that will affect the quality of service enjoyed by customers.</p>
                    <p class="content">11. Customer hereby understand all the risks of use and / or the inability of service provided by XL HOME, for that Customer agrees to indemnify XL HOME from any compensation claim both material and immaterial and other forms of liability arising from the existence of these risks.</p>
                    <p class="content">12. XL HOME will do the installation process following the schedule that has been agreed by the Customer, with standard procedures established by the XL HOME, where during the installation process, the Customer or his/her representative shall be at the location and supervise the whole process until the installation is complete.</p>
                    <p class="content">13. As long as the Customer is still registered as a user of our Services, then the Customer has the obligation to maintain and tend XL HOME devices that are placed in the location. In case of damage / loss of XL HOME supporting hardware, XL HOME will charge the cost of replacement / repair to Customer.</p>
                    <h2 class="header">PROHIBITION AND SANCTIONS</h2>
                    <p class="content">14. For the convenience along with Internet users, Customers are not allowed to perform deliberate actions that interfere with or harm the other party, including but not limited to:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Any action or attempt to cause interference on a network or computer system or causing inconvenience for other parties;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Providing false information of the data and information needed, including identity-related to terms of service provided by XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Rent, resell, and / or divert the use of XL HOME Services (either partially or completely) to any other party without the consent of the XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Make any changes to the configuration of XL HOME Services and / or supporting devices provided by XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Actions or other businesses that may considered to have violated the laws and regulations applicable in the jurisdiction of the Republic of Indonesia.</li>
                    </ol>
                                    <p class="content">15. The customer is prohibited to cause interference to networks and other electronic systems that are related or have a connection with the terms of service provided by XL HOME.</p>
                    <p class="content">16. XL HOME reserves the right to terminate the Services before the Customer claimed to terminate the service subscription under the circumstances:</p>
                    <ol class="order-list">
                    <li class="content" style="list-style-type: lower-alpha;">Customers neglect their obligations in accordance with the procedures and conditions specified by XL HOME;</li>
                    <li class="content" style="list-style-type: lower-alpha;">Customers have violated the prohibitions as listed in Terms of Service for XL HOME Fiber Broadband;</li>
                    <li class="content" style="list-style-type: lower-alpha;">There is a request from the state investigation authorities for the interests of the investigation in accordance with the legal provisions in force in the Republic of Indonesia;</li>
                    </ol>
                    <p class="content">In the event of termination of the Agreement, XL HOME and the Customer agrees to waive the provisions of Article 1266 and 1267 of the Civil Code (KUHPerdata).</p>
                    <p class="content">17. Termination of Services as described in Article 16, is to be followed / preceded by a notice / warning prior to the Customer.</p>
                    <p class="content">18. Customers forbidden to give gifts, tips, and / or other provisions that can be categorized as a provision that is not regulated in terms of service to the installation officers, staff, affiliates, officers, managers, and XL HOME board of directors..</p>
                    <h2 class="header">WARRANTIES AND LIABILITY</h2>
                    <p class="content">19. XL HOME is fully responsible for the quality of service provided to the Customers with the exception of a disturbance resulting from the negligence of the Customer and / or implementation of emergency security measures and other events that occur beyond the control of XL HOME (force majeure) as the service provider, including but not limited to a result of court ruling, rules and regulations of the new law with retroactive effect as well as the decision of the Government Agency in charge of issuing a policy law and regulation relating to XL HOME terms of service in the future.</p>
                    <p class="content">20. XL HOME reserves the right at any time remove, add or modify its Services including the price changes in the future, with advance notification through an announcement in one of XL HOME channel, email blasts, website, and running text (scrolling text), or in other media, except for changes made by the third parties.
                    </p>
                    <p class="content">21. The Customer are required to keep and maintain XL HOME’s devices in customer location so that they are functioning and in good condition and suitable to use starting from the date of subscription until they are returned to XL HOME as the result of the expiration of XL HOME subscription. In case of damage / loss on XL HOME supporting hardware for any reason, except as a result of the state of Force Majeure, XL HOME will charge the cost of replacement / repair to the Customer.</p>
                    <p class="content">22. If any devices belong to XL HOME placed on Customer location is lost, damaged or destroyed due to any cause except as a result of force majeure circumstances and negligence of XL HOME, the Customer must replace the device or reimburse the price of the device when the loss or damage occurs.</p>
                    <p class="content">23. In order to improve the quality of service provided to the customer as well as securing the internal network, XL HOME has the right to perform regular maintenance (scheduled maintenance) that will be announced no later than three (3) calendar days. XL HOME also reserves the right to take security precautions which will be followed by SMS and/or the customer’s primary email.</p>
                    <p class="content">24. For the purpose of checking XL HOME quality service, the Customer shall give permission to XL HOME’s employee to enter and inspect the device at customer’s location. In accordance with the work order showed by XL HOME employee during the visit.</p>
                    <h2 class="header">FEES AND PAYMENT</h2>
                    <p class="content">25. For Terms of Service in accordance with their own kind, XL HOME entitled to charge the following expenses:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">which must be paid by the Customers before the service begins;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Monthly fee according to the type of service and/ or additional facility in accordance with Customer’s request, shall be paid before the payment due date through bank transfer, ATM or any other payment methods.</li>
                        <li class="content" style="list-style-type: lower-alpha;">The additional cost will be applied for additional request of devices, materials and additional services during installation and / or during the subscription period.</li>
                        <li class="content" style="list-style-type: lower-alpha;">The additional cost will be applied for service visit to the customer house based on customer request (without any technical problem) during the subscription period.</li>
                        </ol>
                                    <p class="content">26. XL HOME surcharge fee list are as follows:</p>
                        <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Ethernet cable installation that is out of XL HOME standard or exceeds 1 meter, will be charged an additional fee of Rp. 15,000 (fifteen thousand rupiah) / meter.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Drop cable installation that is out of XL HOME standard or exceeds 100 meter, will be charged an additional fee of Rp. 10,000 (ten thousand rupiah) / meter.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Replacement for the damage of XL Home Setop Box will be charged Rp. 1,000,000 (one million rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Replacement for the damage of XL HOME ONT will be charged Rp. 1,000,000 (one million rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Replacement for the damage of HDMI cable, Remote Control, RCA cable and adapter cables will be charged Rp. 500,000 (five hundred thousand rupiah) / unit</li>
                        <li class="content" style="list-style-type: lower-alpha;">There will be an additional cost for relocation devices for IDR 500,000 (Five hundred thousand rupiah).</li>
                    </ol>
                        <p class="content">27. XL HOME service billing will be notified every month and sent to the Customers through invoice.</p>
                    <p class="content">28. Customers are not allowed to make payments in any form by XL HOME employees and / or officers on the location.</p>
                    <p class="content">29. Minimum subscription period is twelve (12) months, if at any time Customers requires to terminate our Services before twelve (12) months of the subscription period, the Customer must sent written notice not later than 14 (fourteen) days before the termination date and shall pay penalty fee of Rp 1.000.000, - (one million rupiah).</p>
                    <p class="content">30. With the Post-Service Termination and/ or end of the subscription period, XL HOME devices placed in Customer’s location must be returned to XL HOME in complete and good condition, without any defects both visible and hidden. </p>
                    <h2 class="header">LAW AND JURIDICTION</h2>
                    <p class="content">31. Execution of some or all of these policies by one or both parties are not included as a violation of these Terms if such things are caused by Force Majeure circumstances.</p>
                    <p class="content">32. Force Majeure events are the unpredictable, and the broad impact that occurs beyond the power of man, among others, including but not limited to events or natural disasters, disease outbreaks (epidemics), insurrection, riot, war, fire, sabotage, general strike, lightning, breaking up the flow of electricity generally beyond the ability of the parties to resolve it.</p>
                    <p class="content">33. Contents and implementation of these policies are subject to regulation and laws applicable in the jurisdiction of the Republic of Indonesia.</p>
                    <p class="content">34. In case of disputes due to the onset of the content and implementation of these policies, they will be settled amicably directly between the customer and XL HOME.</p>
                    <p class="content">35. If the Customer and XL HOME cannot resolve the dispute amicably, then Customer and XL HOME agreed to take legal action and appoint South Jakarta District Court as the general legal domicile and permanent.</p>
                    <p class="content">36. XL HOME reserves the right to provide information on the identity of registered customers to the investigation authorities in certain circumstances in accordance with the laws and regulations applicable in the territory of the Republic of Indonesia.</p>
                    <p class="content">37. XL Home will not share personal information with companies, organizations and individual outside XL Home, except in the situation described in the XL Axiata Privacy Policy. XL Home may share non-personal information with third parties outside of Xl Home, such as content providers or connected sites. This information may be used to promote XL Home, partner services and content, or be used in other ways, such as for product service or content improvements. </p>
                    <p class="content">38. Termination of service due to customer’s demand or negligence in fulfilling these policies shall not waive the levied fee on the use of services.</p>
                    <p class="content">39. If there has been a conflict or discrepancy between the discovery of Provision of XL HOME Fiber Broadband Service with other Document that is interconnected in the terms of service provided by XL HOME, then the policies that apply are the Terms of Service mentioned in this document.</p>
                    <p class="content">40. If any points from the Terms of Service for XL HOME Fiber Broadband specifically provides that the alternative policies in documents related to XL HOME terms of service to Customer is more applicable to these policies, then the replacement points in the document will be valid as long as they are only valid for the documents in question and are not variations of any policies in the Terms of Service for XL HOME Fiber Broadband and. </p>
                    <p class="content">41. XL HOME has the right to change either partially or totally to the contents of the Terms of Service for Fiber Broadband Service in the future. Every changes can be seen on XL HOME Website.</p>
                    <p class="content"></p>
                    <br>
                    <img src="https://spacergif.org/00d67e.gif">
                    <img src="https://spacergif.org/00d67e.gif">
                </div>mendaftar dan/atau menggunakan Layanan XL HOME, maka Pelanggan dianggap telah membaca, mengerti, memahami dan menyetujui semua isi dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband. Ketentuan ini merupakan salah satu bentuk kesepakatan yang dituangkan dalam sebuah perjanjian yang sah antara Pelanggan dengan PT XL Axiata. Jika Pelanggan tidak menyetujui salah satu, sebagian, atau seluruh isi dari Ketentuan Penyediaan Layanan XL HOME Fiber Broadband, maka Pelanggan tidak diperkenankan menggunakan Layanan sebagaimana yang dimaksud.</p>
                    <h2 class="header">	PENYEDIAAN LAYANAN | SERVICE DELIVERY</h2>
                    <p class="content">1.	PT XL Axiata atau XL adalah perusahaan penyelenggara jasa akses internet, didirikan berdasarkan peraturan dan ketentuan hukum yang berlaku di Negara Republik Indonesia.</p>
                    <p class="content">2.	XL HOME Fiber Broadband atau “Layanan” adalah layanan telekomunikasi dalam bentuk data, suara, dan gambar berupa penyediaan Jasa Akses Internet dan Jasa Internet Teleponi untuk keperluan Publik, Email, dan Jaringan Komunikasi Data, termasuk, namun tidak terbatas, pada produk turunan lainnya dimasa mendatang.</p>
                    <p class="content">3.	Pelanggan adalah Pihak yang terdaftar sebagaimana tercantum dalam Formulir Pendaftaran yang disediakan oleh XL HOME, baik atas nama diri sendiri, perusahaan maupun pihak yang diwakili berdasarkan surat kuasa dan/atau dokumen pembuktian lainnya yang sah secara hukum dan peraturan yang berlaku.</p>
                    <p class="content">4.	Perangkat XL HOME adalah Optical Network Terminal (ONT), Set Top Box/Dekoder Digital, Remote Control dan perangkat pendukung lainnya, termasuk, tetapi tidak terbatas, pada peralatan dan perlengkapan lain yang dibutuhkan dimasa yang akan datang yang terdapat di lokasi Pelanggan, selama peralatan dan perlengkapan tersebut tercatat sebagai milik XL HOME.</p>
                    <p class="content">5.	Lokasi adalah lokasi tempat penyediaan layanan XL HOME Fiber Broadband sebagaimana yang tercantum dalam Formulir Pendaftaran/Dokumen pendukung lainnya.</p>
                    <p class="content">6.	XL HOME akan memberikan Username dan Password (SSID dan password) untuk aksestabilitas dalam menggunakan dan menikmati Layanan. Pelanggan bertanggung jawab sepenuhnya terhadap segala aktivitas penggunaan Layanan dan menjaga kerahasiaan password sebagai suatu informasi rahasia yang patut dijaga kerahasiaannya.</p>
                    <p class="content">7.	Pelanggan mengakui dan bertanggung jawab secara penuh bahwa informasi dan dokumen yang diserahkan kepada XL HOME sebagai suatu persyaratan pendaftaran Layanan merupakan dokumen yang sah secara hukum dan memiliki kebenaran yang sejati.</p>
                    <p class="content">8.	XL HOME akan melakukan proses instalasi untuk Pelanggan apabila telah terpenuhinya syarat-syarat yang ditetapkan oleh XL HOME, termasuk diantarannya persyaratan teknis, Formulir Berlangganan, kopi Identitas Pelanggan (KTP/SIM/KITAS), pembayaran pertama sesuai jenis layanan yang dipilih dan dokumen lainnya.</p>
                    <p class="content">9.	Pelanggan berhak untuk menikmati segala manfaat dan keuntungan yang diperoleh melalui penyediaan Layanan, dengan tetap memperhatikan Syarat dan Ketentuan yang diberlakukan oleh XL HOME sebagai penyedia Layanan, termasuk peraturan dan ketentuan hukum yang berlaku di wilayah hukum Republik Indonesia.</p>
                    <p class="content">10.	Pelanggan dengan ini mengakui dan menyatakan bahwa XL HOME dibebaskan dari bentuk pertanggungjawaban, atas layanan yang digunakan oleh Pelanggan atas ketidakcocokan peralatan dan perlengkapan yang digunakan oleh Pelanggan untuk menikmati Layanan termasuk jika Pelanggan melakukan hubungan kerjasama dengan Pihak Lain dan/atau telah terjadi suatu kombinasi antara perangkat milik XL HOME dengan perangkat milik Pihak Ketiga yang tidak diatur dalam Perjanjian ini baik secara sebagian maupun menyeluruh yang akan mempengaruhi kualitas Layanan yang dinikmati oleh Pelanggan.</p>
                    <p class="content">11.	Pelanggan dengan ini memahami segala resiko atas penggunaan dan/atau ketidaksanggupan Layanan yang disediakan oleh XL HOME, untuk itu Pelanggan bersedia membebaskan XL HOME dari segala tuntutan ganti rugi baik yang bersifat materil maupun inmateril dan bentuk pertanggung jawaban lain yang ditimbulkan dari adanya resiko tersebut.</p>
                    <p class="content">12.	XL HOME akan melakukan proses instalasi sesuai jadwal pengerjaan yang telah disepakati oleh Pelanggan, dengan standar prosedur yang telah ditetapkan oleh XL HOME, dimana selama proses instalasi berlangsung, Pelanggan ataupun perwakilannya wajib berada di lokasi dan mengawasi seluruh proses Instalasi hingga selesai.</p>
                    <p class="content">13.	Selama Pelanggan masih terdaftar sebagai pengguna Layanan, maka Pelanggan memiliki kewajiban untuk menjaga dan merawat Perangkat XL HOME yang ditempatkan di lokasi. Apabila terjadi kerusakan/kehilangan atas Perangkat pendukung layanan XL HOME, maka XL HOME akan membebankan biaya penggantian/perbaikan kepada Pelanggan.</p>
                    <h2 class="header">	LARANGAN DAN SANKSI</h2>
                    <p class="content">14.	Demi kenyamanan bersama pengguna Internet, Pelanggan tidak diperkenankan untuk melakukan tindakan-tindakan yang disengaja sehingga mengganggu atau merugikan pihak lainnya, termasuk tetapi tidak terbatas pada:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Tindakan atau usaha sehingga menimbulkan gangguan pada suatu jaringan atau sistem komputer atau menimbulkan ketidaknyamanan pihak yang berkepentingan;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Memberikan keterangan palsu terhadap data dan informasi yang dibutuhkan termasuk identitas diri terkait penyediaan Layanan yang disediakan oleh XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Menyewakan, menjual kembali, dan/atau mengalihkan penggunaan Layanan XL HOME (baik sebagian atau seluruhnya) kepada pihak lain manapun tanpa persetujuan dari XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Melakukan perubahan apapun terhadap konfigurasi Layanan XL HOME dan/atau perangkat pendukung yang disediakan oleh XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Tindakan atau usaha lain yang dapat dianggap telah melanggar hukum dan peraturan yang berlaku di wilayah yurisdiksi Republik Indonesia.</li>
                    </ol>
                    <p class="content">15.	Pelanggan dilarang melakukan tindakan yang dapat menimbulkan gangguan pada jaringan dan atau sistem elektronik lainnya yang berkaitan atau memiliki keterkaitan dengan penyediaan Layanan yang disediakan oleh XL HOME.</p>
                    <p class="content">16.	XL HOME berhak untuk memutuskan Layanan sebelum Pelanggan menyatakan untuk melakukan pengakhiran masa berlangganan dalam keadaan:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Pelanggan telah melakukan pelanggaran terhadap larangan-larangan sebagaimana yang tercantum dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Adanya permintaan dari pejabat penyidik negara guna kepentingan penyidikan sesuai dengan peraturan dan ketentuan hukum yang berlaku di Negara Republik Indonesia;</li>
                    </ol>
                    <p class="content">17.	Pemutusan Layanan sebagaimana dijelaskan pada pasal 16, akan diikuti/didahului dengan pemberitahuan/peringatan sebelumnya kepada Pelanggan.</p>
                    <p class="content">18.	Pelanggan dilarang untuk memberikan hadiah, tips, dan/atau pemberian lainnya yang dapat dikategorikan sebagai suatu pemberian yang tidak diatur dalam ketentuan penyediaan Layanan kepada petugas instalasi, staff, affiliasi, pegawai, manager, dan jajaran direksi XL HOME.</p>
                    <h2 class="header">		JAMINAN DAN TANGGUNG JAWAB </h2>
                    <p class="content">19.	XL HOME bertanggung jawab penuh atas kualitas layanan yang diberikan kepada Pelanggan terkecuali akibat adanya gangguan yang timbul karena kelalaian Pelanggan dan/atau dilaksanakannya tindakan pengamanan darurat dan peristiwa lainnya yang terjadi diluar kendali XL HOME (force majeure) sebagai penyedia Layanan termasuk tetapi tidak terbatas pada suatu akibat dari adanya putusan pengadilan, ketentuan dan peraturan hukum yang baru dan berlaku surut maupun adanya keputusan dari Instansi Pemerintah yang berwenang dalam mengeluarkan suatu kebijakan peraturan perundang-undangan yang berkaitan dengan penyediaan Layanan XL HOME diwaktu yang akan datang.</p>
                    <p class="content">20.	XL HOME berhak sewaktu-waktu mengurangi, menambah atau mengubah Layanannya termasuk dengan perubahan harga dikemudian hari, dengan pemberitahuan terlebih dahulu melalui pengumuman di salah satu saluran XL HOME, email blast, sms broadcast, website, dan teks berjalan (scrolling text), atau pada media-media lainnya, kecuali perubahan yang dilakukan pihak ketiga.</p>
                    <p class="content">21.	Pelanggan wajib menjaga dan memelihara perangkat milik XL HOME di lokasi Pelanggan agar tetap berfungsi dan dalam keadaan baik serta layak pakai terhitung sejak tanggal berlangganan sampai dengan dikembalikannya ke XL HOME akibat berakhirnya masa Berlangganan dengan XL HOME. Apabila terjadi kerusakan/kehilangan atas Perangkat pendukung Layanan XL HOME karena sebab apapun, kecuali akibat dari keadaan Force Majeure, maka XL HOME akan membebankan biaya penggantian/perbaikan kepada Pelanggan.</p>
                    <p class="content">22.	Apabila perangkat milik XL HOME yang ditempatkan di lokasi Pelanggan hilang, rusak atau musnah karena sebab apapun kecuali akibat dari keadaan Force Majeure dan kelalaian XL HOME, maka Pelanggan harus mengganti perangkat tersebut atau mengganti sesuai dengan harga perangkat saat kehilangan atau kerusakan terjadi.</p>
                    <p class="content">23.	Guna meningkatkan kualitas layanan yang disediakan kepada para Pelanggan serta demi pengamanan jaringan internal, XL HOME berhak untuk melakukan perawatan berkala (scheduled maintenance) yang akan diumumkan selambatnya 3 (tiga) hari kalender. XL HOME juga berhak untuk melakukan tindakan pengamanan darurat yang akan diikuti pemberitahuan melalui email dan/atau SMS ke kontak masing-masing Pelanggan.</p>
                    <p class="content">24.	Untuk keperluan pemeriksaan kualitas Layanan XL HOME, Pelanggan wajib memperkenankan XL HOME untuk dapat memasuki dan memeriksa perangkat di lokasi Pelanggan. Sesuai dengan surat perintah kerja yang ditunjukan oleh karyawan XL HOME ke Pelanggan saat dilakukan kunjungan.</p>
                    <h2 class="header">BIAYA DAN PEMBAYARAN</h2>
                    <p class="content">25.	Atas penyediaan Layanan sesuai dengan jenisnya masing-masing, maka XL HOME berhak atas biaya-biaya berikut ini: </p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Biaya berlangganan, yang wajib dilunasi Pelanggan sebelum Layanan dimulai; First payment.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Biaya bulanan, yang sesuai dengan jenis Layanan dan/atau fasilitas tambahan menurut permintaan Pelanggan, wajib dilunasi pada tanggal jatuh tempo di setiap bulan penagihan melalui Transfer, ATM atau metode pembayaran lainnya.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Biaya tambahan akan dikenakan untuk permintaan tambahan perangkat, material dan service tambahan saat pemasangan dan/atau selama masa berlangganan.</li>
                        <li class="content" style="list-style-type: lower-alpha;">d.	Biaya tambahan akan dikenakan untuk layanan kunjungan teknisi ke rumah pelanggan selama masa berlangganan atas permintaan pelanggan (diluar kendala yang disebabkan oleh gangguan layanan XL Home).</li>
                    </ol>
                    <p class="content">26.	Daftar biaya - biaya tambahan XL HOME adalah sebagai berikut: <br>XL HOME surcharge fee list are as follows: </p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Penarikan kabel ethernet diluar standard XL HOME atau melebihi 1 meter, akan dikenakan biaya tambahan sebesar Rp. 15.000 (lima belas ribu rupiah)/meter;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penarikan kabel Drop/ kabel optic diluar standart XL HOME atau melebihi 100 meter, akan dikenakan biaya tambahan sebesar Rp. 10.000 (Sepuluh ribu rupiah) / meter;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penggantian kerusakan perangkat Set Top Box XL HOME akan dikenakan biaya sebesar Rp. 1.000.000 (satu juta rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penggantian kerusakan ONT XL HOME akan dikenakan biaya sebesar Rp. 1.000.000 (satu juta rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Penggantian kerusakan kabel HDMI, Remote Control, kabel RCA dan kabel adapter akan dikenakan biaya sebesar Rp. 500.000 (lima ratus ribu rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Perpindahan perangkat di lokasi yang sama atau ke lokasi baru, akan dikenakan biaya relokasi sebesar Rp. 500.000 (lima ratus ribu rupiah).</li>
                    </ol>
                    <p class="content">27.    Penagihan atas penggunaan Layanan XL HOME akan dilakukan di setiap Billing Cycle (Periode Tagihan) dan diinformasikan oleh XL HOME melalui Faktur Tagihan/Invoice yang dikirimkan ke email Pelanggan.</p>
                    <p class="content">28.	Pelanggan tidak diperkenankan untuk melakukan pembayaran tagihan dalam bentuk apapun melalui karyawan dan/atau petugas XL HOME di lokasi pemasangan.</p>
                    <p class="content">29.	Minimum masa berlangganan adalah 12 (dua belas) bulan, apabila sewaktu-waktu Pelanggan menginginkan pengakhiran Layanan sebelum 12 (dua belas) bulan masa berlangganan, maka Pelanggan wajib terlebih dahulu memberikan pemberitahuan selambat-lambatnya 14 (empat belas) hari sebelum tanggal pemutusan dan wajib membayar biaya penalti sebesar Rp 1.000.000,- (satu juta rupiah) dan melunasi semua pembayaran yang tertunggak.</p>
                    <p class="content">30.	Dengan Pemutusan Layanan dan/atau telah berakhirnya masa berlangganan, maka perangkat XL HOME yang ditempatkan di lokasi Pelanggan wajib dikembalikan oleh Pelanggan kepada XL HOME dalam keadaan lengkap dan tanpa adanya cacat baik yang terlihat maupun yang tersembunyi.</p>
                    <h2 class="header">	HUKUM DAN LAIN-LAIN</h2>
                    <p class="content">31.	Tidak dilaksanakannya sebagian atau seluruh Ketentuan ini oleh salah satu atau kedua belah pihak tidak termasuk sebagai pelanggaran atas Ketentuan jika hal-hal tersebut disebabkan oleh keadaan Force Majeure (keadaan memaksa).</p>
                    <p class="content">32.	Yang termasuk Force Majeure adalah kejadian-kejadian yang tidak dapat diduga, berdampak luas dan yang terjadi diluar kekuasaan manusia, antara lain termasuk tetapi tidak terbatas pada peristiwa-peristiwa atau bencana alam, wabah penyakit (epidemi), pemberontakan, huru-hara, perang, kebakaran, sabotase, pemogokan umum, petir, putus aliran listrik umum diluar kemampuan para pihak untuk mengatasinya.</p>
                    <p class="content">33.	Isi dan pelaksanaan ketentuan ini tunduk kepada peraturan dan hukum yang berlaku di wilayah jurisdiksi Republik Indonesia.</p>
                    <p class="content">34.	Dalam hal timbulnya perselisihan akibat isi dan pelaksanaan ketentuan ini, maka akan diselesaikan secara musyawarah langsung antara Pelanggan dan XL HOME.</p>
                    <p class="content">35.	Apabila Pelanggan dan XL HOME tidak dapat menyelesaikan perselisihan secara musyawarah, maka Pelanggan dan XL HOME sepakat untuk menempuh jalur hukum dan menunjuk Pengadilan Negeri Jakarta Selatan sebagai domisili hukum umum dan tetap.</p>
                    <p class="content">36.	XL HOME berhak untuk memberikan informasi mengenai identitas Pelanggan terdaftar kepada pejabat penyidik yang berwenang dalam keadaan tertentu sesuai dengan peraturan dan hukum yang berlaku di wilayah Republik Indonesia.</p>
                    <p class="content">XL HOME reserves the right to provide information on the identity of registered customers to the investigation authorities in certain circumstances in accordance with the laws and regulations applicable in the territory of the Republic of Indonesia.</p>                
                    <p class="content">37.	XL Home tidak akan membagikan informasi pribadi dengan perusahaan, organisasi, dan individu diluar XL Home, kecuali dalam situasi yang dijelaskan dalam Kebijakan Privasi XL Axiata. XL Home dapat membagikan informasi non-pribadi kepada pihak ketiga di luar XL Home, seperti penyedia konten atau situs terhubung. Informasi ini dapat digunakan untuk mempromosikan XL Home, mitra layanan dan konten, atau digunakan untuk peningkatan layanan atau konten.</p>
                    <p class="content">38.	Pemutusan layanan akibat permintaan atau kelalaian Pelanggan dalam memenuhi ketentuan ini tidak menghapuskan kewajiban yang terhutang atas penggunaan layanan.</p>
                    <p class="content">39.	Apabila telah terjadi suatu pertentangan atau ditemukannya ketidaksesuaian antara Ketentuan Penyediaan Layanan XL HOME Fiber Broadband dengan Dokumen lain yang masih saling berhubungan dalam penyediaan Layanan yang disediakan oleh XL HOME, maka yang berlaku adalah ketentuan-ketentuan yang berlaku dalam Ketentuan Penyediaan Layanan Fiber Broadband ini.</p>
                    <p class="content">40.	Apabila terdapat ketentuan dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband yang secara khusus mengatur bahwa ketentuan alternatif sebagaimana yang terdapat dalam Dokumen-dokumen yang berkaitan dengan penyediaan Layanan XL HOME kepada Pelanggan lebih berlaku atas ketentuan yang terdapat didalam Ketentuan Penyediaan Layanan Fiber Broadband ini, maka ketentuan pengganti yang terdapat didalam dokumen tersebutlah yang akan berlaku selama hanya berlaku atas Dokumen-dokumen sebagaimana yang dimaksud tersebut dan bukan merupakan variasi dari Ketentuan manapun dalam Ketentuan Penyediaan Layanan XL HOME Fiber Broadband.</p>
                    <p class="content">41.	XL HOME memiliki hak untuk mengubah baik secara sebagian maupun menyeluruh terhadap isi dari Ketentuan Penyediaan Layanan XL HOME Fiber Broadband di kemudian hari. Setiap perubahan dapat dilihat di website XL Home.</p>
                    <p class="content"></p>
            
                    <h2 align="center">	TERMS OF SERVICE <br>
                        XL HOME FIBER BROADBAND 
                    </h2>
                    <p class="content">The following Terms of Service for XL Home Fiber Broadband is managed to set the terms and conditions of PT XL Axiata as a service provider. Customers are required to read carefully as it affect the rights and obligations of customers while using the Service.  </p>
                    <p class="content">By registering and/or using XL HOME service, customers are considered to have read, understand, acknowledge, and agree to the contents in Terms of Service for XL HOME Fiber Broadband. The Terms of Service is a legal agreement set forth between the Customer and PT XL Axiata. If the Customer does not agree to one, some, or all of the contents in Terms of Service for XL HOME Fiber Broadband, then Customer may not use the service as intended.</p>
                    <h2 class="header">SERVICE DELIVERY</h2>
                    <p class="content">1. PT XL Axiata or XL is an internet service provider company, established under the legal provisions applicable in the Republic of Indonesia.</p>
                    <p class="content">2. XL HOME Fiber Broadband or “Services” are telecommunication services in the form of data, sound, and images as Internet Access and Internet Telephony Service Provider intended for public, email, and data communications network, including, but not limited, to other derivative products in the future.</p>
                    <p class="content">3. Customers are the registered Parties as contained in the Registration Form provided by XL HOME, whether on its own behalf, the company or the parties by the power of attorney and / or other evidentiary documents that valid legally and according to regulations.</p>
                    <p class="content">4. XL HOME devices are (Optical Network Terminal (ONT), Set Top Box / Digital Decoder, Remote Control, and other supporting devices, including, but not limited to, hardware and other equipment needed in the future located in Customer’s location, as long as the equipment and supplies are listed as owned by XL HOME.</p>
                    <p class="content">5. Location is the location where XL HOME Fiber Broadband service is provided as written in the Registration Form / Other supporting documents.</p>
                    <p class="content">6. XL HOME will provide the Username and Password that is unique to Customer for accessibility in using and enjoying our Services. Customer is solely responsible for all activities in using our Services and maintaining the confidentiality of the password as a secret information that should be kept confidential.</p>
                    <p class="content">7. Customer acknowledges and fully responsible that the information and documents submitted to the XL HOME as a Service registration requirement is a document that is legally valid and has the real truth.</p>
                    <p class="content">8. XL HOME will do the installation process for the customer if the requirements set by XL HOME have been fulfilled, including the technical requirements in the Subscription Form, copy of your ID (KTP/SIM/KITAS), Receipt of first payment based on the package that you choose and other documents.</p>
                    <p class="content">9. Customers are entitled to receive all the benefits and advantages obtained through the terms of service, with regard to the terms and conditions imposed by XL HOME as a service provider, including legal provisions applicable in the jurisdiction of the Republic of Indonesia.</p>
                    <p class="content">10. Customer hereby acknowledges and states that XL HOME is released from the accountability for services used by the Customer, regarding the incompatibility of equipment and supplies used by the Customer to enjoy the Services including if the Customer has conducted a cooperative relationship with the Other and / or there has been a combination of XL HOME-owned devices with devices that belong to Third Party that is not mentioned under this Agreement either in part or a whole that will affect the quality of service enjoyed by customers.</p>
                    <p class="content">11. Customer hereby understand all the risks of use and / or the inability of service provided by XL HOME, for that Customer agrees to indemnify XL HOME from any compensation claim both material and immaterial and other forms of liability arising from the existence of these risks.</p>
                    <p class="content">12. XL HOME will do the installation process following the schedule that has been agreed by the Customer, with standard procedures established by the XL HOME, where during the installation process, the Customer or his/her representative shall be at the location and supervise the whole process until the installation is complete.</p>
                    <p class="content">13. As long as the Customer is still registered as a user of our Services, then the Customer has the obligation to maintain and tend XL HOME devices that are placed in the location. In case of damage / loss of XL HOME supporting hardware, XL HOME will charge the cost of replacement / repair to Customer.</p>
                    <h2 class="header">PROHIBITION AND SANCTIONS</h2>
                    <p class="content">14. For the convenience along with Internet users, Customers are not allowed to perform deliberate actions that interfere with or harm the other party, including but not limited to:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Any action or attempt to cause interference on a network or computer system or causing inconvenience for other parties;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Providing false information of the data and information needed, including identity-related to terms of service provided by XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Rent, resell, and / or divert the use of XL HOME Services (either partially or completely) to any other party without the consent of the XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Make any changes to the configuration of XL HOME Services and / or supporting devices provided by XL HOME;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Actions or other businesses that may considered to have violated the laws and regulations applicable in the jurisdiction of the Republic of Indonesia.</li>
                    </ol>
                                    <p class="content">15. The customer is prohibited to cause interference to networks and other electronic systems that are related or have a connection with the terms of service provided by XL HOME.</p>
                    <p class="content">16. XL HOME reserves the right to terminate the Services before the Customer claimed to terminate the service subscription under the circumstances:</p>
                    <ol class="order-list">
                    <li class="content" style="list-style-type: lower-alpha;">Customers neglect their obligations in accordance with the procedures and conditions specified by XL HOME;</li>
                    <li class="content" style="list-style-type: lower-alpha;">Customers have violated the prohibitions as listed in Terms of Service for XL HOME Fiber Broadband;</li>
                    <li class="content" style="list-style-type: lower-alpha;">There is a request from the state investigation authorities for the interests of the investigation in accordance with the legal provisions in force in the Republic of Indonesia;</li>
                    </ol>
                    <p class="content">In the event of termination of the Agreement, XL HOME and the Customer agrees to waive the provisions of Article 1266 and 1267 of the Civil Code (KUHPerdata).</p>
                    <p class="content">17. Termination of Services as described in Article 16, is to be followed / preceded by a notice / warning prior to the Customer.</p>
                    <p class="content">18. Customers forbidden to give gifts, tips, and / or other provisions that can be categorized as a provision that is not regulated in terms of service to the installation officers, staff, affiliates, officers, managers, and XL HOME board of directors..</p>
                    <h2 class="header">WARRANTIES AND LIABILITY</h2>
                    <p class="content">19. XL HOME is fully responsible for the quality of service provided to the Customers with the exception of a disturbance resulting from the negligence of the Customer and / or implementation of emergency security measures and other events that occur beyond the control of XL HOME (force majeure) as the service provider, including but not limited to a result of court ruling, rules and regulations of the new law with retroactive effect as well as the decision of the Government Agency in charge of issuing a policy law and regulation relating to XL HOME terms of service in the future.</p>
                    <p class="content">20. XL HOME reserves the right at any time remove, add or modify its Services including the price changes in the future, with advance notification through an announcement in one of XL HOME channel, email blasts, website, and running text (scrolling text), or in other media, except for changes made by the third parties.
                    </p>
                    <p class="content">21. The Customer are required to keep and maintain XL HOME’s devices in customer location so that they are functioning and in good condition and suitable to use starting from the date of subscription until they are returned to XL HOME as the result of the expiration of XL HOME subscription. In case of damage / loss on XL HOME supporting hardware for any reason, except as a result of the state of Force Majeure, XL HOME will charge the cost of replacement / repair to the Customer.</p>
                    <p class="content">22. If any devices belong to XL HOME placed on Customer location is lost, damaged or destroyed due to any cause except as a result of force majeure circumstances and negligence of XL HOME, the Customer must replace the device or reimburse the price of the device when the loss or damage occurs.</p>
                    <p class="content">23. In order to improve the quality of service provided to the customer as well as securing the internal network, XL HOME has the right to perform regular maintenance (scheduled maintenance) that will be announced no later than three (3) calendar days. XL HOME also reserves the right to take security precautions which will be followed by SMS and/or the customer’s primary email.</p>
                    <p class="content">24. For the purpose of checking XL HOME quality service, the Customer shall give permission to XL HOME’s employee to enter and inspect the device at customer’s location. In accordance with the work order showed by XL HOME employee during the visit.</p>
                    <h2 class="header">FEES AND PAYMENT</h2>
                    <p class="content">25. For Terms of Service in accordance with their own kind, XL HOME entitled to charge the following expenses:</p>
                    <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">which must be paid by the Customers before the service begins;</li>
                        <li class="content" style="list-style-type: lower-alpha;">Monthly fee according to the type of service and/ or additional facility in accordance with Customer’s request, shall be paid before the payment due date through bank transfer, ATM or any other payment methods.</li>
                        <li class="content" style="list-style-type: lower-alpha;">The additional cost will be applied for additional request of devices, materials and additional services during installation and / or during the subscription period.</li>
                        <li class="content" style="list-style-type: lower-alpha;">The additional cost will be applied for service visit to the customer house based on customer request (without any technical problem) during the subscription period.</li>
                        </ol>
                                    <p class="content">26. XL HOME surcharge fee list are as follows:</p>
                        <ol class="order-list">
                        <li class="content" style="list-style-type: lower-alpha;">Ethernet cable installation that is out of XL HOME standard or exceeds 1 meter, will be charged an additional fee of Rp. 15,000 (fifteen thousand rupiah) / meter.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Drop cable installation that is out of XL HOME standard or exceeds 100 meter, will be charged an additional fee of Rp. 10,000 (ten thousand rupiah) / meter.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Replacement for the damage of XL Home Setop Box will be charged Rp. 1,000,000 (one million rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Replacement for the damage of XL HOME ONT will be charged Rp. 1,000,000 (one million rupiah) / unit.</li>
                        <li class="content" style="list-style-type: lower-alpha;">Replacement for the damage of HDMI cable, Remote Control, RCA cable and adapter cables will be charged Rp. 500,000 (five hundred thousand rupiah) / unit</li>
                        <li class="content" style="list-style-type: lower-alpha;">There will be an additional cost for relocation devices for IDR 500,000 (Five hundred thousand rupiah).</li>
                    </ol>
                        <p class="content">27. XL HOME service billing will be notified every month and sent to the Customers through invoice.</p>
                    <p class="content">28. Customers are not allowed to make payments in any form by XL HOME employees and / or officers on the location.</p>
                    <p class="content">29. Minimum subscription period is twelve (12) months, if at any time Customers requires to terminate our Services before twelve (12) months of the subscription period, the Customer must sent written notice not later than 14 (fourteen) days before the termination date and shall pay penalty fee of Rp 1.000.000, - (one million rupiah).</p>
                    <p class="content">30. With the Post-Service Termination and/ or end of the subscription period, XL HOME devices placed in Customer’s location must be returned to XL HOME in complete and good condition, without any defects both visible and hidden. </p>
                    <h2 class="header">LAW AND JURIDICTION</h2>
                    <p class="content">31. Execution of some or all of these policies by one or both parties are not included as a violation of these Terms if such things are caused by Force Majeure circumstances.</p>
                    <p class="content">32. Force Majeure events are the unpredictable, and the broad impact that occurs beyond the power of man, among others, including but not limited to events or natural disasters, disease outbreaks (epidemics), insurrection, riot, war, fire, sabotage, general strike, lightning, breaking up the flow of electricity generally beyond the ability of the parties to resolve it.</p>
                    <p class="content">33. Contents and implementation of these policies are subject to regulation and laws applicable in the jurisdiction of the Republic of Indonesia.</p>
                    <p class="content">34. In case of disputes due to the onset of the content and implementation of these policies, they will be settled amicably directly between the customer and XL HOME.</p>
                    <p class="content">35. If the Customer and XL HOME cannot resolve the dispute amicably, then Customer and XL HOME agreed to take legal action and appoint South Jakarta District Court as the general legal domicile and permanent.</p>
                    <p class="content">36. XL HOME reserves the right to provide information on the identity of registered customers to the investigation authorities in certain circumstances in accordance with the laws and regulations applicable in the territory of the Republic of Indonesia.</p>
                    <p class="content">37. XL Home will not share personal information with companies, organizations and individual outside XL Home, except in the situation described in the XL Axiata Privacy Policy. XL Home may share non-personal information with third parties outside of Xl Home, such as content providers or connected sites. This information may be used to promote XL Home, partner services and content, or be used in other ways, such as for product service or content improvements. </p>
                    <p class="content">38. Termination of service due to customer’s demand or negligence in fulfilling these policies shall not waive the levied fee on the use of services.</p>
                    <p class="content">39. If there has been a conflict or discrepancy between the discovery of Provision of XL HOME Fiber Broadband Service with other Document that is interconnected in the terms of service provided by XL HOME, then the policies that apply are the Terms of Service mentioned in this document.</p>
                    <p class="content">40. If any points from the Terms of Service for XL HOME Fiber Broadband specifically provides that the alternative policies in documents related to XL HOME terms of service to Customer is more applicable to these policies, then the replacement points in the document will be valid as long as they are only valid for the documents in question and are not variations of any policies in the Terms of Service for XL HOME Fiber Broadband and. </p>
                    <p class="content">41. XL HOME has the right to change either partially or totally to the contents of the Terms of Service for Fiber Broadband Service in the future. Every changes can be seen on XL HOME Website.</p>
                    <p class="content"></p>
                    <br>
                    <img src="https://spacergif.org/00d67e.gif">
                    <img src="https://spacergif.org/00d67e.gif">
                </div>
            </div>